# waf-config.yml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'WAF configuration for Misight App'

Resources:
  MisightWAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: misight-app-waf-acl
      Description: WAF Web ACL for Misight App
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: MisightWAFWebACL
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWS-AWSManagedRulesCommonRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
        - Name: IPRateLimit
          Priority: 2
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: IPRateLimit
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP

